### ISSUE TITLE
Improve web user interface

### ISSUE THREAD

**Issue by emxsys** [emxsys/callattendant#40]
- [x] Add Dashboard page #41 
- [x] Add CRUD support to Permitted page #38 
- [x] Add CRUD support to Blocked page #39 
- [x] Add voice message symbols/buttons to Call Log page
- [x] Add block caller buttons to Messages page
- [x] Improve mobile/ responsive layout 
- [x] Add Call History page #24
- [ ] ~Enable context menu on Call Log (consider: _manage caller, play voice message_)~
