### ISSUE TITLE
Add support for other countries

### ISSUE THREAD

**Issue by emxsys** [emxsys/callattendant#99]
I would like to add support for other countries.  Currently, the __callattendant__ uses only a U.S.-based online lookup service (NoMoRobo), and the phone numbers use a U.S.-based formatting (XXX-XXX-XXXX).

To add support for other countries, I can identify the following issues and/or needs:
- [x] Changes to the configuration to specify the phone number format and the online lookup service/database.
- [x] Add support for inputting variable phone number formats. #111
- [x] Add support for various phone number display formats. #112
- [x] Add support for various online lookup services and/or databases. #113
- [x] Add support for non-numeric characters in phone numbers. #114 
-  ~Add support for multiple languages (I18N)~ _Deffered. Separate issue._

If you have any insights on these items, please leave a comment.

**Comment by J0hnMatrix** [comment]
Hello,
I can help for the french phone numbers ;-)
